yggdrasil:
  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:
        address: "127.0.0.1:10010"
    logger:
      level: error

  interceptor:
    unaryServer: "logger"
    streamServer: "logger"
    config:
      logger:
        printReqAndRes: true
