// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package genrpc

import (
	"github.com/imkuqin-zw/yggdrasil/pkg/utils/xstrings"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPackage     = protogen.GoImportPath("context")
	statusPackage      = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/status")
	streamPackage      = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/stream")
	clientPackage      = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/client")
	interceptorPackage = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/interceptor")
	serverPackage      = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/server")
	metadataPackage    = protogen.GoImportPath("github.com/imkuqin-zw/yggdrasil/pkg/metadata")
	codePackage        = protogen.GoImportPath("google.golang.org/genproto/googleapis/rpc/code")
)

func GenerateFiles(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}
	generateRpcFile(gen, file)
}

func generateRpcFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_rpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	generateHeader(g, file)
	generateFileContent(gen, file, g)
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func generateFileContent(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the yggdrasil package it is being compiled against.")
	g.P("var _ = new(", metadataPackage.Ident("MD"), ")")
	g.P()

	for _, service := range file.Services {
		if len(service.Methods) > 0 {
			genService(g, service, file)
		}
	}
}

func genService(g *protogen.GeneratedFile, service *protogen.Service, file *protogen.File) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}

	sd := &serviceDesc{
		Filename:              file.GeneratedFilenamePrefix + ".proto",
		ServiceType:           service.GoName,
		ServiceName:           string(service.Desc.FullName()),
		FullServerName:        string(service.Desc.FullName()),
		LowerFirstServiceType: xstrings.StrToLowerFirstCamelCase(service.GoName),
		Context:               g.QualifiedGoIdent(contextPackage.Ident("Context")),
		Code:                  g.QualifiedGoIdent(codePackage.Ident("")),
		Status:                g.QualifiedGoIdent(statusPackage.Ident("")),
		Client:                g.QualifiedGoIdent(clientPackage.Ident("")),
		Server:                g.QualifiedGoIdent(serverPackage.Ident("")),
		Interceptor:           g.QualifiedGoIdent(interceptorPackage.Ident("")),
		Md:                    g.QualifiedGoIdent(metadataPackage.Ident("")),
		NeedStream:            false,
	}
	for _, method := range service.Methods {
		tmp := &methodDesc{
			Name:         method.GoName,
			Input:        g.QualifiedGoIdent(method.Input.GoIdent),
			Output:       g.QualifiedGoIdent(method.Output.GoIdent),
			ClientStream: method.Desc.IsStreamingClient(),
			ServerStream: method.Desc.IsStreamingServer(),
		}
		if tmp.ClientStream || tmp.ServerStream {
			sd.NeedStream = true
		}
		sd.Methods = append(sd.Methods, tmp)
	}
	if sd.NeedStream {
		sd.Stream = g.QualifiedGoIdent(streamPackage.Ident(""))
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute(tpl))
	}
}

const deprecationComment = "// Deprecated: Do not use."
