yggdrasil:
  application:
    namespace: "dev"
  client:
    github.com.imkuqin_zw.yggdrasil.example.sample:
      endpoints:
        - address: "127.0.0.1:55879"
          protocol: "grpc"
  interceptor:
    unaryClient: "logger"
    streamClient: "logger"
    config:
      logger:
        printReqAndRes: true

