yggdrasil:
  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:
        address: "127.0.0.1:55879"

  interceptor:
    unaryServer: "logger"
    streamServer: "logger"
    config:
      logger:
        printReqAndRes: true
#    grpc:
#      host: 127.0.0.1
#      port: 30001
#  tracer: jaeger

#jaeger:
#  endpoint: "http://localhost:14268/api/traces"
#  sampler: 1
