yggdrasil:
  application:
    namespace: "default"
  server:
    protocol:
      - "grpc"

  client:
    github.com.imkuqin_zw.yggdrasil_polaris.example.server:
      resolver: "polaris"
      balancer: "polaris"
  interceptor:
    unaryClient: "logger"
    streamClient: "logger"
    config:
      logger:
        printReqAndRes: true

  registry: "polaris"
  remote:
    logger:
      level: "debug"

polaris:
  client:
    global:
      serverConnector:
        addresses:
          - "192.168.1.5:8091"
      statReporter:
        enable: true
        chain:
          - prometheus
    consumer:
      circuitBreaker:
        enable: true
        chain:
          - errorRate
      serviceRouter:
        enableRecoverAll: false
  registry:
    registerGovernor: true