// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package helloword

import (
	context "context"
	types "github.com/imkuqin-zw/yggdrasil/pkg/types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.

type GreeterClient interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloStream(context.Context) (GreeterSayHelloStreamClient, error)
	SayHelloClientStream(context.Context) (GreeterSayHelloClientStreamClient, error)
	SayHelloServerStream(context.Context, *HelloRequest) (GreeterSayHelloServerStreamClient, error)
}

type GreeterSayHelloStreamClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	types.ClientStream
}

type GreeterSayHelloClientStreamClient interface {
	Send(*HelloRequest) error
	types.ClientStream
}

type GreeterSayHelloServerStreamClient interface {
	CloseAndRecv() (*HelloReply, error)
	Recv() (*HelloReply, error)
	types.ClientStream
}
