// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package helloword

import (
	context "context"
	types "github.com/imkuqin-zw/yggdrasil/pkg/types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.

type GreeterClient interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloStream(context.Context) (GreeterSayHelloStreamClient, error)
	SayHelloClientStream(context.Context) (GreeterSayHelloClientStreamClient, error)
	SayHelloServerStream(context.Context, *HelloRequest) (GreeterSayHelloServerStreamClient, error)
}

type GreeterSayHelloStreamClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	types.ClientStream
}

type GreeterSayHelloClientStreamClient interface {
	Send(*HelloRequest) error
	types.ClientStream
}

type GreeterSayHelloServerStreamClient interface {
	CloseAndRecv() (*HelloReply, error)
	Recv() (*HelloReply, error)
	types.ClientStream
}
