// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package helloword

import (
	context "context"
	errors "github.com/imkuqin-zw/yggdrasil/pkg/errors"
	types "github.com/imkuqin-zw/yggdrasil/pkg/types"
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloStream(GreeterSayHelloStreamServer) error
	SayHelloClientStream(GreeterSayHelloClientStreamServer) error
	SayHelloServerStream(*HelloRequest, GreeterSayHelloServerStreamServer) error
	UnsafeGreeterServer
}

type GreeterSayHelloStreamServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	types.ServerStream
}

type GreeterSayHelloClientStreamServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	types.ServerStream
}

type GreeterSayHelloServerStreamServer interface {
	Send(*HelloReply) error
	types.ServerStream
}

type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, errors.Errorf(code.Code_UNAUTHENTICATED, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SayHelloStream(GreeterSayHelloStreamServer) error {
	return errors.Errorf(code.Code_UNAUTHENTICATED, "method SayHelloStream not implemented")
}
func (UnimplementedGreeterServer) SayHelloClientStream(GreeterSayHelloClientStreamServer) error {
	return errors.Errorf(code.Code_UNAUTHENTICATED, "method SayHelloClientStream not implemented")
}
func (UnimplementedGreeterServer) SayHelloServerStream(*HelloRequest, GreeterSayHelloServerStreamServer) error {
	return errors.Errorf(code.Code_UNAUTHENTICATED, "method SayHelloServerStream not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}
