yggdrasil:
  application:
    namespace: "default"
    version: 2.0.0
  server:
    protocol:
      - "grpc"
  governor:
    port: 3000

  remote:
    logger:
      level: "debug"

  registry: "polaris"

  interceptor:
    unaryServer: "logger,polaris_limit"
    streamServer: "logger"
    config:
      logger:
        printReqAndRes: true

#jaeger:
#  endpoint: "http://localhost:14268/api/traces"
#  sampler: 1

polaris:
  client:
    global:
      serverConnector:
        addresses:
          - "192.168.1.5:8091"
      statReporter:
        enable: true
        chain:
          - prometheus
        plugin:
          prometheus:
            type: "push"
            #            metricPort: 3000
            address: "192.168.1.5:9091"
            interval: "10s"
  registry:
    registerGovernor: true
    metaWithGovernor: true
  source: "polaris_demo_server.yaml"